Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    #config.vm.network "public_network"
    #connfig.vm.network "private_network", ip: "10.0.0.100"
    config.vm.synced_folder "./code", "/home/vagrant", disabled: true
    config.vm.provision "shell", inline: "sudo apt-get update"
    config.vm.provision "shell", path: "./script.sh"
    
end

# Varias maquinas virtuales a la vez

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty64"

    config.vm.define "host_1" do |host|
        host.vm.network "private_network", ip: "10.0.0.100"
    end

    config.vm.define "host_2" do |host|
        host.vm.network "private_network", ip: "10.0.0.101"
    end

end