
Vagrant.configure(2) do |config|
    config.vm.hostname = "main"
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.synced_folder ".", "/vagrant", disabled: true    
end